FROM alpine:3.16

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.sjtug.sjtu.edu.cn/g' /etc/apk/repositories \
    && apk --update add --no-cache \
    curl \
    && wget https://yf5gcar.oss-cn-shanghai.aliyuncs.com/org/Shanghai \
    && mv Shanghai /etc/localtime
